export const SELFIE_SCENARIOS = [
    {
        name: "Luxurious bathroom",
        location: "chic luxurious bathroom with bright lighting",
        outfit: "elegant casual black tank top, gold necklace",
        hair: "messy bun",
    },
    {
        name: "Hotel room window",
        location: "high-rise modern luxury hotel room indoors, city skyline in background",
        outfit: "stylish strapless textured dark top",
        hair: "down, elegant blowout",
    },
    {
        name: "Aesthetic bedroom",
        location: "aesthetic dim lit bedroom, cozy ambiance",
        outfit: "oversized cozy sweater off one shoulder",
        hair: "half up half down",
    },
    {
        name: "Luxury lounge",
        location: "luxury lounge interior chic upscale hotel",
        outfit: "elegant dark minimalist slip dress",
        hair: "sleek straight glass hair",
    },
    {
        name: "Walk-in closet",
        location: "luxurious walk-in closet dressing room",
        outfit: "casual stylish denim and white crop top",
        hair: "loose effortless beach waves",
    },
    {
        name: "Modern hallway",
        location: "modern sleek wealthy hallway",
        outfit: "trendy blazer over a chic top",
        hair: "casual ponytail",
    },
    {
        name: "Luxury Elevator",
        location: "modern luxury elevator interior with warm golden lighting and metal accents",
        outfit: "sleek black turtleneck sweater, silver minimalist jewelry",
        hair: "sharp chin-length classic french bob",
    },
    {
        name: "Chic Cafe Interior",
        location: "interior of a chic parisian cafe, cozy warm lighting, blurred background",
        outfit: "classic breton striped long sleeve top",
        hair: "messy romantic 90s updo with face framing pieces",
    },
    {
        name: "Car Interior",
        location: "inside a high-end luxury car, premium leather seats, daylight streaming through windows",
        outfit: "trendy athleisure set with a plush zip-up hoodie",
        hair: "sleek high ponytail",
    },
    {
        name: "Old Money Library",
        location: "classic old money library with rich oak wood panels, warm dim lamp light",
        outfit: "cashmere turtleneck sweater in camel",
        hair: "defined bouncy curls, extreme volume",
    },
    {
        name: "Vanity Mirror",
        location: "vibrant backstage makeup vanity with soft glowing studio bulbs",
        outfit: "elegant white silk button-down blouse, slightly unbuttoned",
        hair: "feathered layers throughout, 90s supermodel volume",
    },
    {
        name: "Minimalist Studio",
        location: "modern minimalist photography studio, clean lines, soft diffused daylight",
        outfit: "Y2K style cropped baby tee with a cute graphic",
        hair: "long straight hair with blunt bangs across forehead",
    },
    {
        name: "Moody Alternative Room",
        location: "dark moody alternative aesthetic room, subtle red neon lighting in the background",
        outfit: "fishnet long sleeve under a vintage black band tee",
        hair: "textured wavy long bob, lob",
    },
    {
        name: "Aesthetic Boutique",
        location: "trendy high-end fashion boutique interior, soft pastel tones, rack of clothes in background",
        outfit: "pink pastel cardigan with pearl buttons",
        hair: "long bouncy blowout, curtain bangs",
    },
    {
        name: "Sunlit Balcony",
        location: "sunlit balcony overlooking the mediterranean sea, warm light",
        outfit: "breezy white linen summer dress",
        hair: "windswept loose waves",
    },
    {
        name: "Gym Mirror",
        location: "high-end luxury gym mirror, neon lighting, clean equipment in background",
        outfit: "matching premium athletic wear set, leggings and sports bra",
        hair: "high sleek ponytail",
    },
    {
        name: "Art Gallery",
        location: "modern art gallery, bright white walls, abstract paintings",
        outfit: "chic minimalist black turtleneck and trousers",
        hair: "sleek low bun",
    },
    {
        name: "Evening Gala",
        location: "glamorous evening gala red carpet background, sparkling lights",
        outfit: "elegant floor-length sequin evening gown",
        hair: "classic hollywood waves",
    },
    {
        name: "Tropical Beach Resort",
        location: "luxury tropical beach resort, palm trees, clear blue water in background",
        outfit: "designer swimsuit with a sheer cover-up",
        hair: "wet look slicked back hair",
    },
    {
        name: "Cozy Winter Cabin",
        location: "cozy winter log cabin interior, fireplace glowing in the background, snowy window",
        outfit: "thick oversized cable-knit sweater, comfy scarf",
        hair: "messy bun with face-framing pieces",
    },
    {
        name: "Neon City Streets",
        location: "cyberpunk neon-lit city streets at night, blurred rain and lights",
        outfit: "edgy black leather jacket with a graphic band tee",
        hair: "shaggy wolf cut",
    },
    {
        name: "First Class Flight",
        location: "first-class luxury airplane cabin seat, soft window light above the clouds",
        outfit: "chic matching cashmere lounge set",
        hair: "loose romantic curls",
    },
    {
        name: "Vintage Record Store",
        location: "aesthetic vintage record store interior, racks of vinyl, warm retro lighting",
        outfit: "denim overalls and a striped vintage tee",
        hair: "shag with bangs",
    }
];
